name: fetch-ui
run-name: Deploy fetch-ui

on:
  workflow_dispatch:
  push:

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  APP_NAME: fetch-ui
  IMAGE_NAME: dragon699/home-k8s/fetch-ui
  APP_REPO: dragon699/home-k8s
  APP_DEPLOYMENT_FILE: manifests/apps/fetch-ui/fetch-ui.yaml


jobs:

  package:
    runs-on: gha-runner-home
    outputs:
      version: ${{ steps.image_version.outputs.VERSION }}

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Authenticate to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Determine build version
      id: image_version
      run: |
        VERSION_FILE=VERSION
        VERSION=$(cat ${VERSION_FILE})

        if [ $? -ne 0 ] || [ -z "$VERSION" ]; then
          echo "${VERSION_FILE}: Failed to fetch version from file!"

          exit 1
        fi

        echo "VERSION=${VERSION}" >> ${GITHUB_OUTPUT}
        echo "Target image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}"

    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.image_version.outputs.VERSION }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest


  deploy:
    runs-on: gha-runner-home
    needs: package

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        repository: dragon699/home-k8s
        fetch-depth: 0
        ref: main

    - name: Ensure latest code
      run: |
        git config user.name "ActionsBot"
        git fetch origin main
        git pull --rebase origin main

    - name: Update ${{ env.APP_NAME }} manifests
      uses: mikefarah/yq@master
      with:
        cmd: yq -i '.spec.template.spec.containers[0].image = "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.package.outputs.version }}"' ${{ env.APP_DEPLOYMENT_FILE }}

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: "fetch-ui: Bump to v${{ needs.package.outputs.version }}"
        commit_user_name: ActionsBot
        file_pattern: ${{ env.APP_DEPLOYMENT_FILE }}
        push_options: --force-with-lease
