name: fetch-ui
run-name: Deploy fetch-ui

on:
  workflow_dispatch:
  push:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: dragon699/home-k8s/fetch-ui
  APP_REPO: dragon699/home-k8s
  APP_DEPLOYMENT_FILE: manifests/apps/fetch-ui/fetch-ui.yaml


jobs:

  Build:
    runs-on: gha-runner-fetch-ui
    outputs:
      version: ${{ steps.image_version.outputs.VERSION }}

    steps:
    - name: Fetch code
      uses: actions/checkout@v6

    - name: Inspect version
      id: image_version
      run: |
        VERSION_FILE=VERSION
        VERSION=$(cat ${VERSION_FILE})

        if [ $? -ne 0 ] || [ -z "$VERSION" ]; then
          echo "${VERSION_FILE}: Failed to fetch version from file!"

          exit 1
        fi

        echo "VERSION=${VERSION}" >> ${GITHUB_OUTPUT}
        echo "Target image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}"

    - name: Prepare registry auth
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.image_version.outputs.VERSION }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest


  Deploy:
    runs-on: gha-runner-fetch-ui
    needs: Build

    steps:
    - name: Fetch devops code
      uses: actions/checkout@v6
      with:
        repository: ${{ env.APP_REPO }}
        token: ${{ secrets.APP_REPO_TOKEN }}
        fetch-depth: 0
        ref: main

    - name: Fetch latest changes
      run: |
        git config user.name "ActionsBot"
        git fetch origin main
        git pull --rebase origin main

    - name: Bump version
      uses: mikefarah/yq@master
      with:
        cmd: yq -i '.spec.template.spec.containers[0].image = "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.Build.outputs.version }}"' ${{ env.APP_DEPLOYMENT_FILE }}

    - name: Commit changes
      id: deployment_changes
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: "fetch-ui: Bump to v${{ needs.Build.outputs.version }}"
        commit_user_name: ActionsBot
        file_pattern: ${{ env.APP_DEPLOYMENT_FILE }}
        push_options: --force-with-lease

    - name: Deploy
      uses: clowdhaus/argo-cd-action/@main
      if: steps.deployment_changes.outputs.changes_detected == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        download-url: "https://${{ secrets.ARGOCD_SERVER }}/download/argocd-linux-amd64"
        command: app sync fetch-ui
        options: >-
          --auth-token ${{ secrets.ARGOCD_TOKEN }}
          --server ${{ secrets.ARGOCD_SERVER }}
          --grpc-web
